### ISSUE TITLE
No audio on Safari when someone joined and the browser tab is inactive

### ISSUE THREAD

**Issue by laszlominczer** [livekit/client-sdk-js#589]
### Describe the bug

When I joined a room with disabled microphone, and after changing the browser tab on Safari, I didn't hear the newly joined participants audio tracks. But when I changed back to the active room's tab the audio is working again.

### Reproduction

Open the sample app(latest version) in Safari
Join  a room 
Disable the audio
Switch to another browser tab in Safari
Join with another participant in another browser or a different tab
Say something into the microphone

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 49.69 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.2.0 - ~/.nvm/versions/node/v18.2.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.12.2 - ~/.nvm/versions/node/v18.2.0/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 109.0
    Safari: 16.2
```

### Severity

annoyance

**Comment by lukasIO** [comment]
This unfortunately seems to be safari specifically blocking auto play on elements in backgrounded tabs. 
Have you observed any other audio/video solution that has made this work?

**Comment by davidzhao** [comment]
Safari strikes again :(

I guess we could pre-warm a bunch of audio elements?

**Comment by laszlominczer** [comment]
Thanks for your responses, @lukasIO I tried Zoom and Google Meets also, and those were working well.

**Comment by davidzhao** [comment]
This should be fixed by #733 @lukasIO ?

**Comment by lukasIO** [comment]
Not sure, if this addresses the same issue. #733 is solving a (different) auto-play issue specifically for iOS Safari, while this issue affects primarily macOS due to tab switching.

**Comment by svajunas-budrys** [comment]
Still have this problem, are there any plans to deal with it in the near future?

**Comment by svajunas-budrys** [comment]
This seem to work. Thanks a lot!
